name:                teapot
version:             0.1.0.0
github:              "bokesan/teapot"
license:             BSD3
author:              "Christoph Breitkopf"
maintainer:          "chbreitkopf@gmail.com"
copyright:           "2018 Christoph Breitkopf"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/teapot#readme>

dependencies:
- base >= 4.7 && < 5
- time
- http-types
- wai
- warp
- bytestring
- text

library:
  source-dirs: src

executables:
  teapot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - teapot

tests:
  teapot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - teapot
    - tasty
    - tasty-hunit
